# Generated by Django 3.1.2 on 2020-10-18 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('mainDoctor', models.CharField(max_length=140)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
