# Generated by Django 3.1.2 on 2020-10-26 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='patient',
            name='name',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='patient',
            name='mainDoctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitalis.doctor'),
        ),
    ]
