# Generated by Django 3.1.2 on 2020-10-26 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalis', '0002_auto_20201026_0916'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_created', models.DateField(auto_now_add=True)),
                ('text', models.CharField(max_length=2046)),
            ],
            options={
                'ordering': ['date_of_created'],
            },
        ),
        migrations.CreateModel(
            name='Examination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_examination', models.DateTimeField()),
            ],
            options={
                'ordering': ['date_of_examination'],
            },
        ),
        migrations.CreateModel(
            name='ExaminationAction',
            fields=[
                ('name', models.CharField(max_length=254, primary_key=True, serialize=False)),
                ('is_action_paid', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='HealthcareWorker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('date_of_birth', models.DateField(default=None, max_length=8)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='doctor',
            name='date_of_birth',
            field=models.DateField(default=None, max_length=8),
        ),
        migrations.AddField(
            model_name='doctor',
            name='email_field',
            field=models.EmailField(default=None, max_length=254),
        ),
        migrations.AddField(
            model_name='patient',
            name='date_of_birth',
            field=models.DateField(default=None, max_length=8),
        ),
        migrations.AddField(
            model_name='patient',
            name='email_field',
            field=models.EmailField(default=None, max_length=254),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='name',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='patient',
            name='name',
            field=models.CharField(max_length=254),
        ),
        migrations.CreateModel(
            name='TransactionRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_state', models.CharField(choices=[('PD', 'Paid'), ('UD', 'Unpaid'), ('FR', 'Free')], default='FR', max_length=2)),
                ('examination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitalis.examination')),
                ('examinationAction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitalis.examinationaction')),
                ('transaction_approver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitalis.healthcareworker')),
            ],
        ),
        migrations.CreateModel(
            name='HealthConcern',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('description', models.CharField(max_length=2046)),
                ('state', models.CharField(choices=[('WT', 'Waiting'), ('ON', 'Ongoing'), ('TL', 'Terminal'), ('ED', 'Ended')], default='ON', max_length=2)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitalis.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitalis.patient')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ExaminationRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_timestamp', models.DateTimeField(auto_now_add=True)),
                ('state', models.CharField(choices=[('PD', 'Pending'), ('CD', 'Canceled'), ('RD', 'Resolved')], default='PD', max_length=2)),
                ('concern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitalis.healthconcern')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitalis.doctor')),
            ],
            options={
                'ordering': ['created_timestamp'],
            },
        ),
        migrations.AddField(
            model_name='examinationaction',
            name='action_manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitalis.healthcareworker'),
        ),
        migrations.AddField(
            model_name='examination',
            name='actions',
            field=models.ManyToManyField(through='hospitalis.TransactionRequest', to='hospitalis.ExaminationAction'),
        ),
        migrations.AddField(
            model_name='examination',
            name='examinating_doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitalis.doctor'),
        ),
        migrations.AddField(
            model_name='examination',
            name='request_based_on',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitalis.examinationrequest'),
        ),
        migrations.CreateModel(
            name='DoctorReportCommentary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=2046)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitalis.doctorreport')),
            ],
        ),
        migrations.AddField(
            model_name='doctorreport',
            name='about_concern',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitalis.healthconcern'),
        ),
        migrations.AddField(
            model_name='doctorreport',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitalis.doctor'),
        ),
    ]
