# Generated by Django 3.1.2 on 2020-10-26 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalis', '0004_auto_20201026_1033'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactionrequest',
            old_name='examinationAction',
            new_name='examination_action',
        ),
    ]
