# Generated by Django 3.1.2 on 2020-10-28 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalis', '0005_auto_20201026_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthcareworker',
            name='email_field',
            field=models.EmailField(default=None, max_length=254),
        ),
    ]
