# Generated by Django 3.1.2 on 2020-10-28 12:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalis', '0007_doctor_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='age',
        ),
        migrations.AddField(
            model_name='doctor',
            name='active_from',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='doctor',
            name='phone_number',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='doctor',
            name='specializes_in',
            field=models.CharField(default=None, max_length=254),
        ),
        migrations.AddField(
            model_name='doctor',
            name='user_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='healthcareworker',
            name='active_from',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='healthcareworker',
            name='phone_number',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='healthcareworker',
            name='user_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='healthcareworker',
            name='works_for_company',
            field=models.CharField(default=None, max_length=254),
        ),
        migrations.AddField(
            model_name='patient',
            name='active_from',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='patient',
            name='phone_number',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='patient',
            name='user_active',
            field=models.BooleanField(default=True),
        ),
    ]
